# basic python image
FROM python:3.7

# install pika to access rabbitmq
RUN pip install pymongo

# Without this setting, Python never prints anything out.
ENV PYTHONUNBUFFERED=1

# declare the source directory
WORKDIR /usr/src/app/getsize

# copy the file
COPY getsize.py .

# start command
CMD [ "python", "getsize.py" ]
